# Generated by Django 5.1.2 on 2024-12-05 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_iata_num', models.CharField(max_length=10, null=True)),
                ('flight_date', models.DateField(max_length=10, null=True)),
                ('airline', models.CharField(max_length=25, null=True)),
                ('airline_code', models.CharField(max_length=3, null=True)),
                ('departure_city', models.CharField(max_length=50, null=True)),
                ('departure_time', models.DateTimeField(max_length=20, null=True)),
                ('departure_terminal', models.CharField(max_length=2, null=True)),
                ('departure_gate', models.CharField(max_length=3, null=True)),
                ('arrival_city', models.CharField(max_length=50, null=True)),
                ('arrival_time', models.DateTimeField(max_length=20, null=True)),
                ('arrival_terminal', models.CharField(max_length=2, null=True)),
                ('arrival_gate', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ListingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_from_user', models.BooleanField(default=False)),
                ('text', models.TextField(max_length=2500)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('chain_code', models.CharField(blank=True, max_length=10, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True)),
                ('dupe_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_address', models.TextField(blank=True, null=True)),
                ('photo_references', models.JSONField(blank=True, null=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='app.message')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
                ('property_type', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('square_footage', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_type', models.CharField(max_length=50)),
                ('days_on_market', models.IntegerField()),
                ('mls_name', models.CharField(max_length=255)),
                ('mls_number', models.CharField(max_length=255)),
                ('listing_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listingagent')),
                ('listing_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listingoffice')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_type', models.CharField(max_length=50)),
                ('listed_date', models.DateTimeField()),
                ('removed_date', models.DateTimeField(blank=True, null=True)),
                ('days_on_market', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.property')),
            ],
        ),
    ]
