# Generated by Django 5.1.2 on 2024-11-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = []

  operations = [
    migrations.CreateModel(
      name="Conversation",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("title", models.CharField(max_length=250, unique=True)),
      ],
    ),
    migrations.CreateModel(
      name="Message",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("timestamp", models.DateTimeField(auto_now_add=True)),
        ("is_from_user", models.BooleanField(default=False)),
        ("text", models.TextField()),
        (
          "conversation",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            to="app.conversation",
          ),
        ),
      ],
    ),
  ]
