# Generated by Django 5.1.2 on 2024-12-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_terminal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_terminal',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
