# Generated by Django 5.1.2 on 2024-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='state',
        ),
        migrations.AddField(
            model_name='hotel',
            name='chain_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='dupe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='iata_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
