# Generated by Django 5.1.2 on 2024-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_hotel_address_remove_hotel_amenities_and_more'),
    ]

    operations = [


    ]
