# Generated by Django 5.1.2 on 2024-11-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_conversation_city_alter_conversation_reason'),
        ('app', '0007_remove_hotel_address_remove_hotel_amenities_and_more'),
    ]

    operations = [
    ]
