# Generated by Django 5.1.2 on 2024-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_hotel_address_remove_hotel_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='city',
            field=models.CharField(default='Unknown City', max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='reason',
            field=models.CharField(default='Unknown reason', max_length=60),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo_references',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
