# Generated by Django 5.1.2 on 2024-11-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_conversation_city_conversation_reason_and_more'),
    ]

    operations = [

    ]
