# Generated by Django 5.1.2 on 2024-11-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_photo_references_hotel_photo_urls'),
    ]

    operations = [

    ]
