# Generated by Django 5.1.2 on 2024-11-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_message_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
