# Generated by Django 5.1.2 on 2024-11-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_hotel_formatted_address_hotel_google_photo_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='google_photo_reference',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='google_place_id',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_level',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='website',
        ),
    ]
