# Generated by Django 5.1.2 on 2024-11-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_hotel_formatted_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='google_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
