# Generated by Django 5.1.2 on 2024-11-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_hotel_photo_url_hotel_photo_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='photo_urls',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
