# Generated by Django 5.1.2 on 2024-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_hotel_photo_urls_hotel_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo_references',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
