# Generated by Django 5.1.2 on 2024-11-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_hotel_photo_urls_hotel_photo_url'),
        ('app', '0017_remove_hotel_photo_url_hotel_photo_references'),
    ]

    operations = [
    ]
