# Generated by Django 5.1.2 on 2024-12-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_hotel_photo_url_hotel_photo_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_iata_num', models.CharField(max_length=10)),
                ('flight_date', models.DateField(max_length=10)),
                ('airline', models.CharField(max_length=25)),
                ('airline_code', models.CharField(max_length=3)),
                ('departure_time', models.DateTimeField(max_length=20)),
                ('departure_terminal', models.CharField(max_length=2)),
                ('departure_gate', models.CharField(max_length=3)),
                ('arrival_city', models.CharField(max_length=10)),
                ('arrival_time', models.DateTimeField(max_length=20)),
                ('arrival_terminal', models.CharField(max_length=2)),
                ('arrival_gate', models.CharField(max_length=3)),
            ],
        ),
    ]
