# Generated by Django 5.1.2 on 2024-11-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_hotel_photo_url_hotel_photo_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ListingOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('formatted_address', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('property_type', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('square_footage', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('hoa_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_type', models.CharField(max_length=50)),
                ('listed_date', models.DateTimeField()),
                ('removed_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('last_seen_date', models.DateTimeField()),
                ('days_on_market', models.IntegerField()),
                ('mls_name', models.CharField(max_length=255)),
                ('mls_number', models.CharField(max_length=255)),
                ('listing_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listingagent')),
                ('listing_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listingoffice')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_type', models.CharField(max_length=50)),
                ('listed_date', models.DateTimeField()),
                ('removed_date', models.DateTimeField(blank=True, null=True)),
                ('days_on_market', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.property')),
            ],
        ),
    ]
