# Generated by Django 5.1.2 on 2024-12-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_listingagent_listingoffice_property_propertyhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='county',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='hoa_fee',
        ),
        migrations.RemoveField(
            model_name='property',
            name='last_seen_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listed_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='removed_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
