# Generated by Django 5.1.2 on 2024-12-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_flight_arrival_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
