# Generated by Django 5.1.2 on 2024-11-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_listingagent_listingoffice_property_propertyhistory'),
        ('app', '0019_delete_searchresult'),
    ]

    operations = [
    ]
