# Generated by Django 5.1.2 on 2024-12-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_flight_departure_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_gate',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_terminal',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_gate',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_terminal',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_iata_num',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
