# Generated by Django 5.1.2 on 2024-12-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_flight_airline_alter_flight_airline_code_and_more'),
        ('app', '0021_remove_property_address_line1_and_more'),
    ]

    operations = [
    ]
