# Generated by Django 5.1.2 on 2024-12-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_merge_20241204_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
