# Generated by Django 5.1.2 on 2024-12-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_property_address_line1_and_more'),
        ('app', '0023_alter_flight_arrival_city_and_more'),
    ]

    operations = [
    ]
