# Generated by Django 5.1.2 on 2024-12-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20241114_1259'),
        ('app', '0024_merge_20241204_1255'),
    ]

    operations = [
    ]
