# Generated by Django 5.1.2 on 2024-12-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_merge_20241204_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='reason',
            field=models.CharField(max_length=60),
        ),
    ]
