# Generated by Django 5.1.2 on 2024-12-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_property_latitude_property_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='google_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
