# Generated by Django 5.1.2 on 2024-12-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_hotel_google_rating_alter_property_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
