# Generated by Django 5.1.2 on 2025-01-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_gate',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_terminal',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_gate',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_terminal',
        ),
    ]
