# Generated by Django 5.1.2 on 2025-01-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_flight_arrival_gate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_price',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
