# Generated by Django 5.1.2 on 2025-02-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_flight_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
