# Generated by Django 5.1.2 on 2025-03-04 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_preferences'),
        ('app', '0031_alter_flight_airline'),
    ]

    operations = [
    ]
