# Generated by Django 5.1.2 on 2025-04-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_merge_0028_preferences_0031_alter_flight_airline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_price',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_gate',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_terminal',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_gate',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_terminal',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(max_length=20, null=True),
        ),
    ]
