# Generated by Django 5.1.2 on 2025-04-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_flight_flight_price_flight_arrival_gate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
