# Generated by Django 5.1.2 on 2025-04-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_flight_airline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_iata_num',
            new_name='iata',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_price',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
