# Generated by Django 5.1.2 on 2025-04-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_flight_iata_num_flight_iata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='iata',
            new_name='flight_iata_num',
        ),
    ]
