# Generated by Django 5.1.2 on 2025-04-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_iata_flight_flight_iata_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='house_rating',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
