x-app: &default-app
  build:
    context: "."
    dockerfile: src/Dockerfile
  volumes:
    - ./src:/src
  restart: "unless-stopped"

services:
  web:
    <<: *default-app
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  tailwind:
    <<: *default-app
    command: "python manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
      