premade_moving = [
  "Diversity",
  "Employment",
  "Healthcare",
  "Housing",
  "Public Transportation",
  "Safety",
  "Schools",
  "Things to do",
  "Traffic",
  "Weather",
]

premade_travel = [
  "Activities for Kids",
  "Attractions",
  "Events",
  "Flights",
  "Food and Restaurants",
  "Hotels",
  "Museums",
  "Nightlife",
  "Safety",
  "Stores",
  "Things to do",
  "Weather",
]

cities = [
  "Albuquerque, NM",
  "Arlington, TX",
  "Atlanta, GA",
  "Austin, TX",
  "Baltimore, MD",
  "Boston, MA",
  "Charlotte, NC",
  "Chicago, IL",
  "Cleveland, OH",
  "Colorado Springs, CO",
  "Columbus, OH",
  "Dallas, TX",
  "Denver, CO",
  "Detroit, MI",
  "El Paso, TX",
  "Fort Worth, TX",
  "Fresno, CA",
  "Houston, TX",
  "Indianapolis, IN",
  "Jacksonville, FL",
  "Kansas City, MO",
  "Las Vegas, NV",
  "Long Beach, CA",
  "Los Angeles, CA",
  "Louisville, KY",
  "Memphis, TN",
  "Mesa, AZ",
  "Miami, FL",
  "Milwaukee, WI",
  "Minneapolis, MN",
  "Nashville, TN",
  "New Orleans, LA",
  "New York, NY",
  "Oakland, CA",
  "Oklahoma City, OK",
  "Omaha, NE",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Portland, OR",
  "Raleigh, NC",
  "Reno, NV",
  "Sacramento, CA",
  "San Antonio, TX",
  "San Diego, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Seattle, WA",
  "Tampa, FL",
  "Tulsa, OK",
  "Tucson, AZ",
  "Virginia Beach, VA",
  "Washington, DC",
  "Wichita, KS",
]
